services:
  oracle:
    image: 'gvenzl/oracle-free:23.4-full-faststart'
    environment:
      - 'ORACLE_RANDOM_PASSWORD=true'
      - 'APP_USER=pocuser'
      - 'APP_USER_PASSWORD=pocpassword'
      - 'ORACLE_DATABASE=POC_GRAAL'
    ports:
      - 1521:1521
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s