services:
  oracle:
    image: 'gvenzl/oracle-free:23.4-full-faststart'
    environment:
      - 'ORACLE_RANDOM_PASSWORD=true'
      - 'APP_USER=GRAAL_JS'
      - 'APP_USER_PASSWORD=password'
      - 'ORACLE_DATABASE=GRAAL'
    ports:
      - "1521:1521"
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s