spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/GRAAL
    username: GRAAL_JS
    password: password
  flyway:
    locations: classpath:migration/default
    url: jdbc:oracle:thin:@//localhost:1521/GRAAL
    user: GRAAL_JS
    password: password
    enabled: true