spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/POC_GRAAL
    username: pocuser
    password: pocpassword
  flyway:
    locations: classpath:migration/default
    url: jdbc:oracle:thin:@//localhost:1521/POC_GRAAL
    user: pocuser
    password: pocpassword
    enabled: true