CREATE TABLE LOGIC (
   NAME VARCHAR2(255) PRIMARY KEY,
   DESCRIPTION VARCHAR2(255),
   SCRIPT CLOB,
   TYPE VARCHAR2(50)
);

CREATE TABLE PARAMETER (
   NAME VARCHAR2(255),
   DESCRIPTION VARCHAR2(255),
   PARAMETER_TYPE VARCHAR2(50),
   JAVA_TYPE VARCHAR2(50),
   VALUE VARCHAR2(255),
   LOGIC_NAME VARCHAR2(255),
   CONSTRAINT PK_PARAMETER PRIMARY KEY (NAME, LOGIC_NAME),
   CONSTRAINT FK_LOGIC FOREIGN KEY (LOGIC_NAME) REFERENCES LOGIC(NAME)
);

INSERT INTO LOGIC (NAME, DESCRIPTION, TYPE, SCRIPT)
VALUES ('Sum of A, B and C', 'The sum of the preset parameters A and B with the dynamic parameter C', 'INTEGER',
        'let a; let b; let c; ' ||
        'function main() { ' ||
        '   return a + b + c; ' ||
        '}');

INSERT INTO PARAMETER (NAME, DESCRIPTION, PARAMETER_TYPE, JAVA_TYPE, VALUE, LOGIC_NAME)
VALUES ('a', 'Valor A', 'PRESET', 'INTEGER', '50', 'Sum of A, B and C');

INSERT INTO PARAMETER (NAME, DESCRIPTION, PARAMETER_TYPE, JAVA_TYPE, VALUE, LOGIC_NAME)
VALUES ('b', 'Valor B', 'PRESET', 'INTEGER', '40', 'Sum of A, B and C');

INSERT INTO PARAMETER (NAME, DESCRIPTION, PARAMETER_TYPE, JAVA_TYPE, LOGIC_NAME)
VALUES ('c', 'Valor C', 'DYNAMIC', 'INTEGER', 'Sum of A, B and C');